### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Review by MichaelHatherly — APPROVED** [review]

**Comment by MichaelHatherly** [comment]
Thanks @PallHaraldsson.

**Comment by PallHaraldsson** [comment]
You have same typo at https://github.com/MichaelHatherly/ContentHashes.jl text to right, so maybe, a habit.

I suppose you saw at juliaup, not sure I'm using incorrectly, want this package perfect, even helping this little bit.

**Comment by MichaelHatherly** [comment]
Very much a habit of not proof reading things.

**Comment by PallHaraldsson** [comment]
For now not opening a new issue here, even though something related to your package broke juliaup, since juliaup with nothing more bus errors, that seems clearly a bug in juliaup. Still, do you have any ideas? Since you might know what changed?

**Comment by PallHaraldsson** [comment]
FYI: in case you missed my EDITs at the juliaup issue (I was having unexplained internet packet loss issue, maybe because of USB or other hardware issue), before juliaup and your packages, but now see:

```
$ cat /usr/bin/vi >/dev/null

$ cat /usr/bin/man >/dev/null
cat: /usr/bin/man: Input/output error
```

Still noted about sysimage specific to 1.7.3 (or 1.7).

**Comment by MichaelHatherly** [comment]
And that was with `--startup-file=no` passed as well? What's `juliaup st` showing you?

**Comment by PallHaraldsson** [comment]
julia or anything related is not to blame:

```
$ julia --startup-file=no
Bus error (core dumped)

since as cat above show, an I/O error or filesystem, still not completely broken since I can run as:

$ .julia/juliaup/julia-1.8.0-rc3+0.x64/bin/julia
```

I basically posted to cat part to show juliaup/sysimage no longer my immediate problem, and for you to not look into it.

**Pull request merged**
